SOURSES= main.c rungekut.c diff_eq_models.c makeSimulation.c
HEADERS= rungekut.h diff_eq_models.h makeSimulation.h

all:	simulator

simulator:	$(SOURSES) $(HEADERS)
	gcc	$(SOURSES) $(HEADERS) -o simulator
